### ISSUE TITLE
 'Non-absolute path found' error 

### ISSUE THREAD

**Issue by kirillburton** [YStrauch/swagger-object-validator#36]
Hi there!

I've just updated to version 1.4.3 and started to receive these errors. 
Downgrading to 1.4.0 helps (.1 and .2 seems to have the same problem)

Relative path I'm using seems to work as intended in 1.4.0:
`var validator = new swaggerValidator.Handler('logs-schema.yaml', {allowAdditionalProperties : true});`

Absolute paths still work in 1.4.3 though

Error stacktrace:
`Error: Non-absolute path found, internal logic should have converted relative paths to absolute
    at _loadFromString (/Users/kirillburton/.../node_modules/swagger-object-validator/lib/helpers/loader.js:98:19)
    at loader (/Users/kirillburton/.../node_modules/swagger-object-validator/lib/helpers/loader.js:23:16)
    at new Handler (/Users/kirillburton/.../node_modules/swagger-object-validator/lib/handler.js:29:48)
    at Object.<anonymous> (/Users/kirillburton/.../swagger-test-test.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
    at internal/main/run_main_module.js:17:11`

**Comment by YStrauch** [comment]
Duplicates #35 which was closed by the author - I'll let this one open.

Do you have spec file(s) to reproduce this issue so I can work on a fix?

**Comment by YStrauch** [comment]
Oh I think I just realised it's not specific to a spec but if you load a spec by relative path. No need to provide a spec.

**Comment by kirillburton** [comment]
You can basically download a sample petstore spec from here: https://editor.swagger.io/

Then get it to a folder with a script like:
`
var swaggerValidator = require('swagger-object-validator');
var validator = new swaggerValidator.Handler('swagger.json', {allowAdditionalProperties : true});

var pet = {
    id: 'This is not a number',
    foo: 'bar',
    tag: [
        'This is an optional argument, but it',
        'Should be a String, not an Array of Strings'
    ]
}

validator.validateModel(pet, 'Pet', function (err, result) {
    console.log(result.humanReadable());
})`  

Seems to be the same output as my spec which I unfortunately can't share

**Comment by YStrauch** [comment]
This should be fixed with 1.4.4 - closing for now
